version: "2.1"

networks:
  public:
    driver: "bridge"
  private:
    driver: "bridge"

volumes:
  cache:
    driver: "local"
  logs:
    driver: "local"
{{- if ne node_version "None" }}
  node_modules:
    driver: "local"
  node_output:
    driver: "local"
{{- end }}

services:
  php:
    image: "php:{{ php_version }}"
    working_dir: "/var/www"
    volumes:
      - ".:/var/www:ro"
      - "cache:/var/www/{{ application_cache_directory | trimSpace }}:rw"
      - "logs:/var/www/{{ application_log_directory | trimSpace }}:rw"
    networks:
      - "public"
      - "private"
    {{- if or (eq php_version "5.6-apache") (eq php_version "7-apache") }}
    ports:
      - "{{ if ne php_expose_port "None" }}{{ php_expose_port }}:{{ end }}80"{{ end }}
    depends_on:
      {{- if ne mysql_version "None"}}
      mysql:
        condition: service_healthy
      {{- end -}}

{{- if and (ne php_version "5.6-apache") (ne php_version "7-apache") }}

  nginx:
    image: "nginx:latest"
    volumes_from:
      - "php"
    ports:
      - "{{ php_expose_port }}:80"
    networks:
      - "public"
      - "private"{{ end -}}

{{- if ne node_version "None" }}

  node:
    image: "node:{{ node_version }}"
    working_dir: "/var/www"
    entrypoint: "npm"
    command: "run develop"
    volumes_from:
      - php
    volumes:
      - "node_modules:/var/www/node_modules:rw"
      - "node_output:/var/www/{{ node_output_directory }}:rw"
    networks:
      - "private"{{ end -}}

{{- if ne mysql_version "None" }}

  mysql:
    image: "mysql:{{ mysql_version }}"
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    networks:
      - "private"
    healthcheck:
      test: ["CMD-SHELL", "mysql -uuser -ppassword -e 'SHOW TABLES' database"]
      interval: 2s
      retries: 10
      timeout: 1s{{ end -}}

{{- if ne postgres_version "None" }}

  postgresql:
    image: "postgres:{{ postgres_version }}"
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - "private"{{ end -}}

{{- if ne memcached_version "None" }}

  memcached:
    image: "memcached:{{ memcached_version }}"
    networks:
      - "private"{{ end -}}

{{- if ne redis_version "None" }}

  redis:
    image: "redis:{{ redis_version }}"
    networks:
      - "private"{{ end -}}

{{- if ne elasticsearch_version "None" }}

  elasticsearch:
    image: elasticsearch:{{ elasticsearch_version }}
    networks:
      - "private"{{ end -}}

{{- if ne rabbitmq_version "None" }}

  rabbitmq:
    image: "rabbitmq:{{ rabbitmq_version }}"
    ports:
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    networks:
      - "private"{{ end -}}

{{- if ne neo4j_version "None" }}

  neo4j:
    image: "neo4j:{{ neo4j_version }}"
    networks:
      - "private"{{ end -}}

